<?php
/**
 * Implements hook_menu_block_blocks().
 */
function main_links_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'main_links-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => '',
      'level'       => 2,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}

